Update to git stripspace

diff --git a/home/bin/stripper b/home/bin/stripper
--- a/home/bin/stripper
+++ b/home/bin/stripper
@@ -1,3 +1,16 @@
-#!/usr/bin/env sh
-# removes trailing whitespace froma  file
-perl -pi -e 's/[ \t]+$//' $*
+#!/bin/bash
+
+if [ -z $1 ] ; then
+  echo "Missing filename(s)"
+  exit 1
+elif [ ! -e $1 ] ; then
+  echo Cannot file requested filename: $1
+  exit 1
+fi
+for file in $* ; do
+    echo Stripping $file
+    tmpfile=/tmp/stripper.$$
+    cp $file $tmpfile
+    git stripspace < $tmpfile > $file
+    rm $tmpfile
+done
